query getCardsUpdatedAt($locale: String!, $version: Int!) {
  all_card_updated: all_card_updated_by_version(where: { locale: { _eq: $locale }, version: { _eq: $version } }) {
    translation_updated_at
    cards_updated_at
  }
}

query getTranslationData($locale: String!) {
  faction_name(where: { locale: { _eq: $locale } }) {
    code
    name
  }
  card_type_name(where: { locale: { _eq: $locale } }) {
    code
    name
  }
  card_subtype_name(where: { locale: { _eq: $locale } }) {
    code
    name
  }
  card_encounter_set(where: { locale: { _eq: $locale _neq: "en" } }) {
    ...EncounterSet
  }
  english_encounters: card_encounter_set(where: { locale: { _eq: "en" } }) {
    ...EncounterSet
  }
  cycle {
    ...Cycle
    translations(where: { locale: { _eq: $locale } }) {
      name
    }
    packs {
      ...Pack
      translations(where: { locale: { _eq: $locale } }) {
        name
      }
    }
  }
}

query getPlayerCards($locale: String!, $version: Int!) {
  all_card(
    where: {
      version: { _lte: $version }
      encounter_code: { _is_null: true }
    }
  ) {
    ...SingleCard
    translations(where: { locale: { _eq: $locale } }) {
      ...CoreCardText
    }
  }
  taboo_set(where: { active: { _eq: true } }) {
    ...TabooSet
  }
  all_card_updated_by_version(where: { locale: { _eq: $locale }, version: { _eq: $version } }) {
    translation_updated_at
    cards_updated_at
  }
}

query getEncounterCards($locale: String!, $version: Int!) {
  all_card(
    where: {
      version: { _lte: $version }
      encounter_code: { _is_null: false }
    }
  ) {
    ...SingleCard
    translations(where: { locale: { _eq: $locale } }) {
      ...CoreCardText
    }
  }
}

query getCardFaq($code: String!) {
  faq_by_pk(code: $code) {
    text
  }
}